In [2]:
!pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 KB 4.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: pyarrow>=15.0.0 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (18.1.0)
Requirement already satisfied: fsspec[http]<=2024.12.0,>=2023.1.0 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (2024.9.0)
Requirement already satisfied: requests>=2.32.2 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (2.32.3)
Requirement already satisfied: numpy>=1.17 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (1.24.4)
Requirement already satisfied: packaging in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (24.1)
Requirement already satisfied: tqdm>=4.66.3 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (4.66.5)
Requirement already satisfied: huggingface-hub>=0.24.0 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (0.27.0)
Requirement already satisfied: aiohttp in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (3.11.11)
Collecting dill<0.3.9,>=0.3.0
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 KB 318.5 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: filelock in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (3.16.1)
Collecting multiprocess<0.70.17
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 KB 7.9 MB/s eta 0:00:00
Requirement already satisfied: pandas in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (2.0.3)
Collecting xxhash
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 KB 8.9 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /home/nikolay/.local/lib/python3.10/site-packages (from datasets) (6.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: frozenlist>=1.1.1 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: propcache>=0.2.0 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: attrs>=17.3.0 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: aiosignal>=1.1.2 in /home/nikolay/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/nikolay/.local/lib/python3.10/site-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/nikolay/.local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/nikolay/.local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /home/nikolay/.local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/nikolay/.local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2024.8.30)
Requirement already satisfied: tzdata>=2022.1 in /home/nikolay/.local/lib/python3.10/site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /home/nikolay/.local/lib/python3.10/site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/nikolay/.local/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.2 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [7]:
import os
import torch 
import logging
import pandas as pd
import numpy as np
from PIL import Image
import torch.nn as nn 
from datasets import load_dataset, load_from_disk
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

In [5]:
dataset_with_butterflies = load_from_disk('/home/nikolay/thesis/tiger-fox-elephant/ddpm/src/thesis/tiger-fox-elephant/ddpm/src/data/butterflies_dataset')
print(dataset_with_butterflies)

DatasetDict({
    train: Dataset({
        features: ['image_url', 'image_alt', 'id', 'name', 'scientific_name', 'gender', 'taxonomy', 'region', 'locality', 'date', 'usnm_no', 'guid', 'edan_url', 'source', 'stage', 'image', 'image_hash', 'sim_score'],
        num_rows: 1000
    })
})

In [9]:
df = pd.DataFrame(dataset_with_butterflies['train'])
df.head()

,image_url,image_alt,id,name,scientific_name,gender,taxonomy,region,locality,date,usnm_no,guid,edan_url,source,stage,image,image_hash,sim_score
0,https://ids.si.edu/ids/deliveryService?id=ark:...,view Paper Kite digital asset number 1,ark:/65665/m3b302800a43ef46b8a7a87a7b1eb06ab6,Paper Kite,Idea leuconoe,None,"Animalia, Arthropoda, Hexapoda, Insecta, Lepid...","US Mid Atlantic (PA, NJ, MD, DE, DC, VA, WV)","NMNH Butterfly Pavilion, North America, United...",None,EO401041,http://n2t.net/ark:/65665/35f90bc1d-2e3c-4798-...,edanmdm:nmnheducation_11038234,Smithsonian Education and Outreach collections,None,<PIL.PngImagePlugin.PngImageFile image mode=RG...,fb0b8749d437efc70a26e54212b3572c,0.805520
1,https://ids.si.edu/ids/deliveryService?id=ark:...,view Doris Longwing digital asset number 1,ark:/65665/m351f75857f81840acb01d0eb82f2a1784,Doris Longwing,Heliconius doris,None,"Animalia, Arthropoda, Hexapoda, Insecta, Lepid...","US Mid Atlantic (PA, NJ, MD, DE, DC, VA, WV)","NMNH Insect Zoo, North America, United States,...",None,EO401027,http://n2t.net/ark:/65665/3f4d0cc10-f3b4-4323-...,edanmdm:nmnheducation_11038220,Smithsonian Education and Outreach collections,None,<PIL.PngImagePlugin.PngImageFile image mode=RG...,9657726e69494021d1c9929ee7b375fa,0.810842
2,https://ids.si.edu/ids/deliveryService?id=ark:...,"view Asian Swallowtail, Chinese Yellow Swallow...",ark:/65665/m3ac764368a66846179e863101219b6fec,"Asian Swallowtail, Chinese Yellow Swallowtail",Papilio xuthus,None,"Animalia, Arthropoda, Hexapoda, Insecta, Lepid...","US Mid Atlantic (PA, NJ, MD, DE, DC, VA, WV)","NMNH Butterfly Pavilion, North America, United...",None,EO401045,http://n2t.net/ark:/65665/33446acdf-f0fd-44f0-...,edanmdm:nmnheducation_11038238,Smithsonian Education and Outreach collections,None,<PIL.PngImagePlugin.PngImageFile image mode=RG...,9303ab0ac75fd0d3047ba987d268f871,0.813563
3,https://ids.si.edu/ids/deliveryService?id=ark:...,view Postman digital asset number 1,ark:/65665/m3855802e6e88c48c58eec449d6e811677,Postman,Heliconius melpomene sticheli,None,"Animalia, Arthropoda, Hexapoda, Insecta, Lepid...","US Mid Atlantic (PA, NJ, MD, DE, DC, VA, WV)","NMNH Insect Zoo, North America, United States,...",None,EO401024,http://n2t.net/ark:/65665/359f1f2d7-bd05-4964-...,edanmdm:nmnheducation_11038217,Smithsonian Education and Outreach collections,None,<PIL.PngImagePlugin.PngImageFile image mode=RG...,3726a5faf63c3d70db5d433705b53ba9,0.813736
4,https://ids.si.edu/ids/deliveryService?id=ark:...,"view Red Postman, Small Postman digital asset ...",ark:/65665/m3e3f4435a245b4a9d9e94a80bd5c0d4a9,"Red Postman, Small Postman",Heliconius erato notabilis,None,"Animalia, Arthropoda, Hexapoda, Insecta, Lepid...","US Mid Atlantic (PA, NJ, MD, DE, DC, VA, WV)","NMNH Insect Zoo, North America, United States,...",None,EO401021,http://n2t.net/ark:/65665/3f50ca15b-8f27-45c7-...,edanmdm:nmnheducation_11038213,Smithsonian Education and Outreach collections,None,<PIL.PngImagePlugin.PngImageFile image mode=RG...,3aa4d93629910b3fe1165c4fc20033fc,0.814460

In [11]:
df = df[['image_url', 'id', 'name']]

In [12]:
df.head()

,image_url,id,name
0,https://ids.si.edu/ids/deliveryService?id=ark:...,ark:/65665/m3b302800a43ef46b8a7a87a7b1eb06ab6,Paper Kite
1,https://ids.si.edu/ids/deliveryService?id=ark:...,ark:/65665/m351f75857f81840acb01d0eb82f2a1784,Doris Longwing
2,https://ids.si.edu/ids/deliveryService?id=ark:...,ark:/65665/m3ac764368a66846179e863101219b6fec,"Asian Swallowtail, Chinese Yellow Swallowtail"
3,https://ids.si.edu/ids/deliveryService?id=ark:...,ark:/65665/m3855802e6e88c48c58eec449d6e811677,Postman
4,https://ids.si.edu/ids/deliveryService?id=ark:...,ark:/65665/m3e3f4435a245b4a9d9e94a80bd5c0d4a9,"Red Postman, Small Postman"

In [14]:
import os
import requests
from PIL import Image
from io import BytesIO

def save_images_from_urls(df, output_path):
    output_dir = os.path.join(output_path, 'images')
    
    os.makedirs(output_dir, exist_ok=True)

    for i, row in df.iterrows():
        try:
            response = requests.get(row['image_url'], stream=True, timeout=10)
            response.raise_for_status() 
            
            image = Image.open(BytesIO(response.content))
            
            file_id = row['id'].split('/')[-1] 
            filename = os.path.join(output_dir, f'{file_id}.jpg')
            
            if image.mode != 'RGB':
                image = image.convert('RGB')
                
            image.save(filename)
            print(f'Saved: {filename}')
            
        except Exception as e:
            print(f'Error with {row["image_url"]}: {str(e)}')

save_images_from_urls(df, output_path='/home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data')

Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b302800a43ef46b8a7a87a7b1eb06ab6.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m351f75857f81840acb01d0eb82f2a1784.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3ac764368a66846179e863101219b6fec.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3855802e6e88c48c58eec449d6e811677.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3e3f4435a245b4a9d9e94a80bd5c0d4a9.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m32663c77db7964deb9afb658b6ae0c9f1.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37bed76876a8a4f388ff496cf165368f6.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m369e4727a4fe8423ebc4c93b8241cd493.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b2a7387f6ad8446cb680c0dd973d3ff6.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m311f2539d1f6b401393d7c21a6c491c89.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37c7a8430f8d0456588d3bda9ee88d788.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m367538bc961ce4cfa8be851826d10f7c7.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m323f99f934005420f87306544162b47c4.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bb7a6141be1e43298d4d11ba1e833ce5.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m387aa9c2d1bda4068a026be021ed75a32.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m303f9cee087f04ff9b1f6fd2000634c26.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3dae2ba69707845488f7337135176b28a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m39737d7ef5c064c55906465a731d641e0.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3c3a183536a104e92bb840f2a6a3857ab.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m310983a30a2164845a3a045ca24d369aa.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m35f3ab63197cd49c7a8f584cf47938658.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m355980031fc04408eb030a872dc25cb97.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m392a9641acf5c4122a7b0a40d8d06cdc9.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026346.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3a14fa8f97c154f208d6ff56d263dda40.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36c1577618aa544aeb4119c01529df070.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026377.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b60e2781777f42a6be6237308d272a16.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026059.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m348feac493aa448eb947e52bc13006be8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3a919837bdc3d4d5fa847bcc275b1c36a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3916b5ed599d3473a8fcc403024952c76.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37592bd6efdc548d58c0e65ea08d62384.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3891c8b5930174c4397aa8a5768e31a13.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m32a351353be424d6fbb582a7a6637905b.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3325de92eb8da46ad8e53c8f9f4708a32.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37df4f574b17d4b29a8717e6839bce133.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3aaa82d8319c9471c87e24f8903075f8c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m31b3ed26cfee44325ac1adcbcfa251bab.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m343b671d567274667878eb91ba833048a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m384985ff9de7f44e5b15771148fc86228.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b0ad270bcdb74924a6d801bc64429fc7.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3c1baa91664fb4a4792a37706ab1dc46b.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m394a0103741ee44c39277d8b71f76dc75.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3c70e17cf30314fd4ad86afa7d1ebf49f.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3102990018fa14473bf84541075e19540.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m357dc5965036646b9a8cfd2d8154f8146.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3eb142b73ff6a4335bd26f1bfa121d181.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m345cdc94ad0da4485ba0e50336ee2b373.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b0861e37774d4249ae71501b4706321c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m30ed20eba97d74914910aaf4f7de76202.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3c3c3bfdfb61048b5b009ba71057421c8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d91be671506d420aa591e5aeeb8608c7.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m346d30133565f41028cd42d397060dec4.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m32eed767a28df4405ac2cbc7226d993db.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m320952de97cbe4971984358052fb08653.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m366c517f6f04148869b47014b73c25f34.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m34ee68c07c06944bd83bd389617be9a8e.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m349ef181afff544fa901f6394e530f3fa.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m31f85b76336004eac9c0adab3b4d16828.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m365482209327c4a11ba80227e94484ebe.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bfdd82b0bb444df5b04451836f3f6770.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m371b16bfa4aa5446e979f05d0cb2fdb39.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m307ed085f02894fbfb84f7940890f6dee.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3383f224cd3aa4fa3b611e827e700dc09.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bee4bcc8738a412eb3f02d1863339b43.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3108b5a49f58c490a822c2845afb2d928.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3195b157b7b8d41359ff9b5694bb8c3f3.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3dacdf2a0250c4808a1e201f356853d6e.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3e57a0ffe81ff4f87895ae975b28d2f3b.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b777a4fc1f80453095a3bfe0c21c7f2c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d5213faa8be845a88e3ed8f5c3eea867.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026410.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d771375e0e474e4b8bd6457553f1aad8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37e3c072343784823a08da2bbe88b39db.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3a2fb07f042f644a68cb5a1ee1f366a4c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m357fabb79b6254ae9aec28b700baf8445.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3744c03fd6e87430896501775458984c5.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m362bdb293c95944749cde76103c4d7f21.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026243.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3eca5afff1f194e028f1ad2d4994af868.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026293.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m34832d6497134428c915ca6e8c66a9d3c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m34fb999ff508c4053b0f17f4d247f1951.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m35efed136e36840739c2fbb6a655bb821.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3810606b2591d42f0bda58dbcf07f1cac.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3cd8a1187dd7f450ea8d4c296f8992245.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026341.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m38f73718f7e244ae1884c5822bd9c64a4.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3448c9f8911ce43e59ba454e4019b47c6.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3aeac33f7acfe45bab6061ab22b4f2bac.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m349312bfbfab547bb889c4f1b84ea14ef.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026167.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b59523e1724c47f3aac63dcfb3303c97.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m372c6bbceaea44ded93b25c567466ddd9.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m38d94ae0e3341436b90b773efab29561b.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3e7ba7c720d3e4a028fc991543c092377.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m30a10742294234219b064e3e06ba49de4.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3a080b67b5b3a4c0ab8ae34be9315eea4.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m342d78ffc5d3649cbbe79d5ad83941026.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37c28d87a790f49008699346de65652db.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3db76cda7d647477193d05c7fa6d8e7c8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m388dd725046124702af14684b63e7257a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m336b22ec152e3426fbad87b87b7a02abb.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3de35eb2169c048fa8e24fdca35510e27.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m34e409dcd2db847d3a645a172e28f38bf.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3eff482a3dd9347119211b9edc6a8b6ba.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3795676a8dee948f8b63d931593f04855.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36e8ce1e90e1b413c9dbb2295922f77c0.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m368d4624c048346f5a071b2e3b058ff1a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3cfc88c3e1c9b44efa9988a27ea28eb77.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3c11f8d8f865349209e912a69eddc30c5.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m352cc6488c9324fa9b610a502681f4896.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m30d8838f4eeea43f6b9ac783ea83eda18.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m32fc60d8eda164210bf08e4f30467efbb.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m35cb17ca9e4b646b58a9988a1aa43ba70.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m35e57d6447c73477a8b93a8cc139a5da8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m34e6f82ed7c1248d5909bdb7be715df8c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36735af2e67a14adb8ccdb6f660e3cc47.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026113.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3eb7d7d7229df4b009ce3628cc95e73e9.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m30d8f35a928d44f2f8450ee6be55d21fa.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36bb20c8a41494e23956c625fc05f7dfe.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37b694c2d09fd4d0d9e557bc9ea1d2f73.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36be571a2a34347a690ec685f283b246d.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b9fc23c4fe6f4efc89d8331237ef4079.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3e1f7b60ff208460fa60d4c504beb80c2.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3324b53e48edf4280bd1b041f314a6be8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3caaa4f93754e480895328b8d922af63a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m349d6240f6ebe4d29a74f1c7438691955.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m38995d887ce7f433f852790fc0999d8f2.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bcd8aeaa75ba46ca90763399486cf03a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m302b73767aa50424b8f2c3b26a71321e8.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m37f802f1f06fd47e9b5aeeec404006be2.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b8a5d3c78f124f418fb8f2ba322efc94.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m396dae9ebe4db4a0888f1cae5c33190d0.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3f1b1f9355a2c46e5996aaf067ed56399.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m39891801def8348c6ac01bc89eaf49d0f.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026461.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36b2252d64d6646eea35e61032d99138b.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m38bd5bb2fb290426080b0d99cdd1436b1.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3ba90a28cc9cf4062bdd7346281026d35.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m314b61c93f9c74b2093bd7fa1649143e0.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m38235d8341d9b4645859cbfb089166895.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d38a7e6ea292487e9bfbacc9310a944e.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m39ab086ec9789465d81eb6ddea559c077.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m35751143bbe9d45b69d3890cc7ce1870e.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3cd182e36583d437ca85d08fd2a64fbac.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3f394c2b55e5245bbb9194a73dd5153ec.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3005b391ab8b44f36b980a21a16e3d45f.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m344d280588c62488897ad63eeb56612e6.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3e99670a425844a0a9494cf1f97a8fa4f.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m322232e44ee2b44c6b14bf1ae6f1d8aa4.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m33a1dbea3307f479bae45b30cc881e01a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m38db8d7aede65443bbde1e776571bff80.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d3ecec3fa39f47a582a137edef640d88.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m33ecdafaf1d0c4890b37937a04804c736.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3f2f193e646f14c838864dd0312aa1bac.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d44bc8325aa3419d8c1dfe8d9e7c8dbf.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m30958c5b4d2b1453d9896ca75f79feea1.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3744d5e70f0a542d9a45fe78ad31f9d99.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m379ff8928f8814d45afd569b3dd91371c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m365089543abe64f299de49497d011d5ae.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3b5eb5ccf8e73405d9f75cbf0f9de6667.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3ccdfe21052fb40378090809ea64d96b2.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m39d68478514f44a2c8a3106acbc9e94ab.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3f4c70157f746461cb6ef5d676542072c.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m39bf3dac208b840b292ed37b3190a9cce.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m30c1e7765ae9d4396b00fe767af7238eb.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3a8fc7f8d295d4a919432b772834eae34.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bbb1a381e693429c8af521f8c5e78369.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m385501fe41a7c438a9606d039055a3a9e.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d014997b49c8458d8c0d821820b2dff9.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m31e67cf37aea54f46bee8b5d3ae7fb0b5.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3f069a46302a1471e99c9d5d0de55bfa2.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m338976596da1b4b3fb2d3fddb4b7412c3.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m36a13a3bf8f074655ab5ccfb6b72ad977.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14025922.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bb942c700c474baf843917944425a6da.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m39ce4dc9269854ce288ff82c28ed2ef68.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m355c07efbf90d475cbc2f3802894d9a7a.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/?irn=14026015.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m31fd0174d7f574607acc7ff2201b78828.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3243c192dce0c478a9cf018b260846d6d.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m34c38cd51790c4bf39710aed48cf91ae7.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3bcd57fa2e6624f69b64be3be76e0a881.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3d89ef7d5c9144645b98810e4da19325b.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m3be27a368e9264b55bed6c7f9ca02dd54.jpg
Saved: /home/nikolay/thesis/tiger-fox-elephant/ddpm/src/data/images/m389a0c234accc4fac943ca7865e6cbfc8.jpg